Feat: archive projects
techmatters/terraso-backend pull request #619
Opened 2023-06-29 18:46 UTC by jodiezhuu

## Description
Create graphql mutation for archiving projects

### Related Issues
Fixes #565

2023-06-29 19:27 UTC, paulschreiber requested changes

2023-06-29 19:27 UTC, paulschreiber commented on terraso_backend/apps/project_management/migrations/0009_archive_projects.py
> +# Generated by Django 4.2.1 on 2023-05-26 19:40
issue: add copyright notice

2023-06-29 19:27 UTC, paulschreiber commented on terraso_backend/apps/project_management/permission_rules.py
> +    return project.is_manager(user)
```suggestion
    return project.is_manager(user)
    
```

2023-07-06 17:41 UTC, david-code approved these changes

2023-07-06 18:02 UTC, paulschreiber approved these changes

2023-07-06 18:41 UTC, merged