refactor: Membership list model for groups and landscapes
techmatters/terraso-backend pull request #997
Opened 2023-11-22 18:12 UTC by josebui

## Description

This is a really big PR, but I organized the commits by section (for most of the changes) so ideally if you check commit by commit the changes isolated to specific components will be there so that you can chek the related changes, hopefully that is good enough to review this.

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added

### Related Issues
- https://github.com/techmatters/terraso-product/issues/415

2023-11-22 20:33 UTC, paulschreiber requested changes

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/groups_memberships.py
> +        )
```suggestion
        user_role = kwargs.get("user_role", group_collaboration_roles.ROLE_MEMBER)
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to approve Membership, but it was not found",
```suggestion
                "Attempt to approve Story Map Membership, but it was not found",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to approve a Membership, but user was not found",
```suggestion
                "Attempt to approve a Story Map Membership, but user was not found",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to approve a Membership, but user has no permission",
```suggestion
                "Attempt to approve a Story Map Membership, but user has no permission",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to approve Membership, but there was an error",
```suggestion
                "Attempt to approve Story Map Membership, but there was an error",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to approve a Membership, but user was not found",
```suggestion
                "Attempt to approve a Story Map Membership, but user was not found",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to approve Membership, but it was not found",
```suggestion
                "Attempt to approve Story Map Membership, but it was not found",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to approve Membership, but user does not match",
```suggestion
                "Attempt to approve Story Map Membership, but user does not match",
```
Under what circumstances does the user not match?

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to approve a Membership, but user has no permission",
```suggestion
                "Attempt to approve a Story Map Membership, but user has no permission",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to approve Membership, but there was an error",
```suggestion
                "Attempt to approve Story Membership, but there was an error",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to delete Story Map Memberships, but it was not found",
```suggestion
                "Attempt to delete Story Map Membership, but it was not found",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to delete Story Map Memberships, but story map was not found",
```suggestion
                "Attempt to delete Story Map Membership, but story map was not found",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to delete Story Map Memberships, but user has no permission",
```suggestion
                "Attempt to delete Story Map Membership, but user has no permission",
```

2023-11-22 20:33 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/story_maps_memberships.py
> +                "Attempt to save Story Map Memberships, but story map was not found",
```suggestion
                "Attempt to save Story Map Membership, but story map was not found",
```

2023-11-22 20:36 UTC, paulschreiber requested changes

2023-11-22 20:36 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/groups_memberships.py
> +                "Attempt to save Story Map Memberships, but story map was not found",
```suggestion
                "Attempt to save Group Membership, but story map was not found",
```

2023-11-22 20:36 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/groups_memberships.py
> +                "Attempt to update a Membership, but cannot remove last manager",
```suggestion
                "Attempt to update a Group Membership, but cannot remove last manager",
```

2023-11-22 20:36 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/groups_memberships.py
> +                "Attempt to delete Group Memberships, but user lacks permission",
```suggestion
                "Attempt to delete Group Membership, but user lacks permission",
```

2023-11-22 20:36 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/landscapes_memberships.py
> +                "Attempt to save Landscape Memberships, but landscape was not found",
```suggestion
                "Attempt to save Landscape Membership, but landscape was not found",
```

2023-11-22 20:36 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/landscapes_memberships.py
> +                "Attempt to delete Landscape Memberships, but user lacks permission",
```suggestion
                "Attempt to delete Landscape Membership, but user lacks permission",
```

2023-11-23 17:31 UTC, josebui commented on terraso_backend/apps/core/permission_rules.py
> +def validate_managers_count(user, membership, entity):
@paulschreiber yes, that is it

2023-11-23 17:32 UTC, josebui commented on terraso_backend/apps/graphql/schema/groups.py
> +        membership_type = kwargs.pop("membership_type") if "membership_type" in kwargs else None
@paulschreiber this is not the same `pop` removes the key from the dictionary `get` is not doing that

2023-11-27 16:16 UTC, paulschreiber commented on terraso_backend/apps/graphql/schema/groups.py
> +        membership_type = kwargs.pop("membership_type") if "membership_type" in kwargs else None
Ah. Looks like `pop()` also supports a default value.

2023-11-29 16:03 UTC, paulschreiber approved these changes

2023-12-04 20:48 UTC, merged